### ISSUE TITLE
End progress not being captured correctly for non-USA countries

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#122] opened 2021-11-22 08:59 UTC
All the tile get "failed" but they are actually completed

<img width="682" alt="Schermata 2021-11-22 alle 09 53 14" src="https://user-images.githubusercontent.com/51291350/142832020-137a07d2-7552-427a-b429-0069b958c539.png">

**Comment by jjjchens235** [comment] 2021-11-22 16:58
To figure out if the quiz is complete, the script uses regex matching English words. Failing because not English.

I could potentially in the future add some regex that matches based on more loose criteria (\w.* instead of hardcoded words).

**Comment by Affoghiamoci** [comment] 2021-11-22 17:03
what words in english use to check te complete of quiz? might i change it

**Comment by jjjchens235** [comment] 2022-01-01 16:13
#144 will solve this issue.

**Comment by jjjchens235** [comment] 2022-01-03 13:52
Actually, 144 won't solve this issue. It will fix the final offer status in the log, but for each individual quiz, it will still show as incomplete.

#### Dev implementation notes
Find a different way to identify if an offer is complete, either
- based on some element in the page
- based on the json from `get_dashboard()` (once punchcard feature is released)

#### Priority
This currently only effects non-US users. On the other hand, the current implementation is not robust, and it's an interesting problem.

**Comment by Affoghiamoci** [comment] 2022-01-17 13:17
I tried to change the "you earned" in my language, but it still doesn't work, so I was wondering if it was a problem where my header is from the English version, could it change?

**Comment by jjjchens235** [comment] 2022-01-17 13:48
can you provide the code you updated to?

**Comment by jjjchens235** [comment] 2022-06-02 10:23
I'm going to start closing out all the non_usa's as I cannot reproduce/fix these errors myself.

**Closed by jjjchens235** 2022-06-02 10:23 UTC
Labels: bug, non_usa
