### ISSUE TITLE
Mobile search only gets 50/100 daily points

### ISSUE THREAD

**Issue by Skytek65** [jjjchens235/bing-rewards#117] opened 2021-11-21 06:18 UTC
If past a level 1 account you can earn 100 points for mobile searches although this script will only do 50/100 of those points for mobile searches.

**Comment by jjjchens235** [comment] 2021-11-22 16:56
Hi - thanks for bringing this up. 

This issue started plaguing me a while back, and I'm not sure if it's a driver issue.

When you run in no-headless mode, it shows what the issue is. The search term is not being sent to the search box and the search box remains empty. This usually happens only on the 7th search or onward (user has mobile 35-50 points).

if anyone can shed light on this, that would be great.

**Comment by Goldenfreddy0703** [comment] 2021-11-26 15:31
Hey there, so i tried the no headless mode but did not see what the issue was. It failed to complete its mobile search and idk why either. 

It could possibly be that the searches are going way too fast which is why the points don't update in time. I would recommend putting a delay when the search result comes up, it delays for a second and goes to the microsft result page in order for it to update on how much search points it has.

**Comment by jjjchens235** [comment] 2021-11-27 23:43
Hey, thanks for taking a look. I'm not sure it has to do with how fast the searches are going as there is code that makes sure that the search box element is accessible before the code proceeds. Furthermore, the code usually fails after x searches in, and once it fails once, it never recovers. If it was just a delay issue, it should recover sometimes.  I could be wrong though, lmk if adding a delay fixes it for you.

I ran the code again in -nhl mode, this time with some extra print statements. Console output [here](https://pastebin.com/NHk2vMXx).
 `query` represents the search term that is pulled from google trends API.

And `search_box_val` represents the search box's element value. The query value is being entered into the search bar, so they should match.

Notice that  starting at query `chet holmgrem` , the search progress is stuck at 45/100. At this point, the browser would show the search-box to be completely blank.

However, the the console shows that the element value is correct `search_box_val: chet holmgren`. So for some reason, while the element value is correct, the UI isn't displaying the value properly.

**Comment by Goldenfreddy0703** [comment] 2021-11-28 06:19
Hey thank you for getting back on this issue, you are right and I think it's not the delay. I personally still have no clue why it's stuck at 45% but when you said that the gui isn't displaying the value properly, I think it could be due to the website itself. I think what your script is doing when it does the mobile searches is that it looks at the results on the website where it shows 0/100, does a mobile search then goes back to it to check its results again and I think once it gets to 45%, the website could have not displayed a result after that 45% which is why it could be causing issue. If I'm correct, a way to resolve that would probably be doing a page refresh after every mobile search so it can check the results after the website has been refreshed.

**Comment by Goldenfreddy0703** [comment] 2021-11-28 17:02
Ok this is fascinating, I just did mobile searches but when you go back the result page, its not updating unless you refresh the page so i think that could be the issue.

**Comment by jjjchens235** [comment] 2021-11-29 01:35
Refreshing the search page does the trick for me- I'm not sure if that's what you meant.

**Comment by Goldenfreddy0703** [comment] 2021-11-29 01:54
Do you think your script can refresh the page after it's done with a mobile search so that your script can go over 45%

**Comment by jjjchens235** [comment] 2021-11-29 02:51
i added logic to refresh the search page when the progress is not being updated. If you're referring to the results page, that page is already updated.

Code has been pushed to master, closing this now, if it doesn't fix the issue, feel free to re-open, thanks for your help!

**Closed by jjjchens235** 2021-11-29 02:51 UTC

**Comment by Goldenfreddy0703** [comment] 2021-11-29 03:40
Hey anytime and thank you. I will check it out in 2 hours or tomorrow and see if this fixed it, thank you

**Comment by Goldenfreddy0703** [comment] 2021-11-29 19:18
Hey to i checked it out and it works really well now, thank you so much for fixing this and you are the best.

**Comment by Goldenfreddy0703** [comment] 2021-12-21 20:26
Hey @jjjchens235 this issue is happening again sadly.
