### ISSUE TITLE
Multiple docker issues..

### ISSUE THREAD

**Issue by JourneyOver** [jjjchens235/bing-rewards#290] opened 2022-10-15 01:43 UTC
Following the [container installation](https://github.com/jjjchens235/bing-rewards#container-installation), and the [compose file](https://github.com/jjjchens235/bing-rewards/blob/master/compose.yaml), I get a symlink permission denied error whenever it's trying to symlink the logs directory.

I've got the permissions set correctly and the config portion works just fine (other than when I restart the container it complains about the file already existing). I've tried with removing `UMASK=022` from the env variables, I've tried changing the mapping in the compose from `/bing` to `/bing-rewards/BingRewards/logs` but that brings up a different issue of `ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/bing-rewards/BingRewards/requirements.txt'` for some reason.

if I create the folders myself, I just end up getting a different error about the file exists, but it doesn't do any symlinks and the log files do not end up getting updated in the /bing folder,

if I remove the mapping in the compose for logs completely, it symlinks just fine with no issues at all, but then if I go to add the mapping back it just starts up with the problems all over again..

this is currently my compose file:
```
---
version: "3.8"

services:

  bing-rewards:
    image: docker.io/killerherts/bing-rewards:latest
    container_name: bing-rewards
    hostname: bing-rewards
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/Docker/Apps/BingRewards/config:/config
      - /mnt/Docker/Apps/BingRewards/logs:/bing
    stdin_open: true
    tty: true

networks:
  bunni_network:
    external: true
```

I've tried with having `UMASK=022` in the env section, I've tried with changing the `- /mnt/Docker/Apps/BingRewards/logs:/bing` to `/bing-rewards/BingRewards/logs` and everything else I've explained above.

**Comment by JourneyOver** [comment] 2022-10-15 08:27
Wow actually there is way more going on than just the logs issue.. Left it to run and when it got to a point where it hit the 8 hour mark for the first time (I just left the default cron since it seems to reset anything I do with the cron if I restart the container for any reason), it started to run the `script.sh` script multiple times over (it had started multiple jobs with different wait times) causing the cpu to start spiking it's way up to 100% ontop of it consuming ram like crazy..

idk the docker setup for this needs way more work to it; it seems..

**Comment by Lexxior** [comment] 2022-10-15 09:57
Had the same issue with docker, up to the point where it crashed my system and only a hard reset fixed it

**Comment by JourneyOver** [comment] 2022-10-15 10:13
Yea mine nearly crashed as well, thankfully I was able to catch it in time and stop the container (which even stopping it all was pretty slow and laggy as hell) otherwise if I had let the container run for just a slight bit longer it'd probably of straight up crashed everything.

one thing I can def see is wrong for sure is that the cronjob they have by default is set to run the script.sh file every minute between the 8-9 hour mark (instead of just once every 8 hours) which is what is causing the CPU/RAM spike leading to the possible crashing of system eventually.

Doesn't help that even if you are to change some things like the cron, the way things are setup in this it all gets reset once you restart the container for whatever reason.

**Comment by Killerherts** [comment] 2022-10-15 23:48
You cannot place the logs into the bing-rewards directory as that would prevent you from doing the git clone as files would already be inside of it hence why you get the requirements error @JourneyOver 

The cron issue does need to be corrected. I'll look into the log permission issue error is likely caused by the touch command trying to create the file when it already exists. Should be fixable with a file check for the log than only create if the file already exists.

**Comment by JourneyOver** [comment] 2022-10-16 01:17
@Killerherts cron issue just needs a simple switch of `* */8 * * *` to `0 */8 * * *` to work correctly and stop the whole secondary issue, but I think a smart thing to do would be to allow users to pass a env variable, that way if someone wants the change the default, it won't get reset back to default any time the container gets restarted.

**Comment by Killerherts** [comment] 2022-10-16 01:43
> @Killerherts cron issue just needs a simple switch of `* */8 * * *` to `0 */8 * * *` to work correctly and stop the whole secondary issue, but I think a smart thing to do would be to allow users to pass a env variable, that way if someone wants to change the default, it won't get reset back to default any time the container gets restarted.

If you have the time submit a PR for adding the env var.

**Comment by JourneyOver** [comment] 2022-10-16 03:11
> If you have the time submit a PR for adding the env var

Ya I'll look into it when I have some time and see if I can figure it out for adding a env variable for the cron stuff, I'm not superversed in docker stuff (dockerfiles and all that) right now as I'm still kind of learning things as I go xD

**Comment by JourneyOver** [comment] 2022-10-16 06:33
just making a mental note and for possibly someone to fix: seems that for some reason the container does not follow the `TZ` value fully (even though tzdata is installed), doing `date` shows the correct time for whats set in `TZ`, but doing `cat /etc/timezone` shows `Etc/UTC`. Due to this, the script (and cron) seems to follow the UTC time instead of the TZ time.


current solution is just to map:

```
- /etc/timezone:/etc/timezone:ro
- /etc/localtime:/etc/localtime:ro
```

in either the docker-compose file or run command whichever the person is doing.

**Comment by fexofenadine** [comment] 2022-10-16 07:45
I'm happy to add the environment variables for the cron job and timezone if you need hands

Also the file creation/existing check

**Comment by Killerherts** [comment] 2022-10-16 08:27
> I'm happy to add the environment variables for the cron job and timezone if you need hands
> 
> Also the file creation/existing check

@fexofenadine the docker feature needs to be rewritten to make easier to follow and make changes. Currently, it is pulling down jj's repo each time we run the container. This was to make sure it was always up to date with any changes and because of my lack of understanding on GitHub action. I have gotten my actions sorted image builds can happen automatically allowing me to take a more traditional path to setting up the container. 

I have started on these changes tonight but held off until I spoke to JJ so I know the route they would like to on the main repo. I think this is the most logical approach as it makes the container far easier to understand and behave in a more expected manner. 

Going this route avoid most of the items that were complaints on my original build updates will simply be handled by maintaining the image. Since log files don't need to be copied in after the build process has started we won't have the log file permission issue ether. 

I was just going to leave a env for the cron job so changes will be ephemeral.

**Comment by fexofenadine** [comment] 2022-10-16 08:52
@Killerherts ok that sounds awesome, appreciate your work on this feature

the offer stands though, please let me know if you need work done that you don't have the time for, I have a decent amount of experience with that side of things

which actually reminds me, should a separate repo be made (bing-rewards-docker or something, with just the dockerfile, and the start scripts and other bits and bobs) for maintenance purposes? I'm thinking something like how the linuxserver guys handle it

**Comment by Killerherts** [comment] 2022-10-16 16:30
Fex that's exactly what I meant when I said we should probably relook at our approach. I had originally done it without a git clone. The room at the time wanted thing to go this way. I'll probably take a few days to get this done since its almost Monday so if you get time feel free to jump on it.

**Comment by ForceConstant** [comment] 2022-10-17 12:04
I have been using docker succesfully for the last few weeks, but have changed a few things from default. 
1. Create new entry.sh that only calls bing rewards and exists. Basically merged in the script.sh
2. Use external cron to start docker container

**Comment by JourneyOver** [comment] 2022-10-17 21:41
> I have been using docker succesfully for the last few weeks, but have changed a few things from default.
> 
> 1. Create new entry.sh that only calls bing rewards and exists. Basically merged in the script.sh
> 2. Use external cron to start docker container

So what your doing is starting the container up and having it run with script.sh indefintely, but after the first run it just sits there (kind of how like it is with entry.sh does currently other than running BingRewards.py right away) until your external cron executes the command inside of the container? 

why not just go a step further and set up a sleep task in the script.sh (could even be randomized a tiny bit) that'll recall the command needed to run the BingRewards.py after the initial run instead of using cron at all

**Comment by fexofenadine** [comment] 2022-10-17 21:52
I think having a bash script that runs indefinitely is probably not the way to go, if it hangs or crashes it will bring the whole thing to a halt and can't recover. At least with cron, it will start ontime every time. cron is designed for scheduled events specifically and is stable excellent at its job

here's a reasonable pro-con list to help decide: https://www.the-lazy-dev.com/en/cron-vs-sleep-which-is-better/

**Comment by Lexxior** [comment] 2022-10-25 10:41
> [PR](https://github.com/jjjchens235/bing-rewards/pull/294)

Thanks for the update!
However, for me it still doesn't work

I get this

```
config.json created/updated successfully
+ tail -f /bing-rewards/BingRewards/logs/cronBing.log
```
and then it just stops - the cronBing.log file exists but is empty

**Comment by JourneyOver** [comment] 2022-10-25 19:04
@Lexxior that's because it hasn't even done it's first "actual" run, you have to wait the alloted time in your cron before it does it's run and starts to fill out the logs.

**Comment by Killerherts** [comment] 2022-10-25 23:17
> > [PR](https://github.com/jjjchens235/bing-rewards/pull/294)
> 
> Thanks for the update!
> However, for me it still doesn't work
> 
> I get this
> 
> ```
> config.json created/updated successfully
> + tail -f /bing-rewards/BingRewards/logs/cronBing.log
> ```
> and then it just stops - the cronBing.log file exists but is empty

You can also force it to run by 
docker exec bing-rewards BingRewards.py -nsb

**Comment by Lexxior** [comment] 2022-10-26 19:29
> @Lexxior that's because it hasn't even done it's first "actual" run, you have to wait the alloted time in your cron before it does it's run and starts to fill out the logs.

I waited more than 2 hours, yet nothing changed


> You can also force it to run by
> `docker exec bing-rewards BingRewards.py -nsb`
> This is not merged with master yet so you need to use the DockerFix tag as stated in the pr.

I tried this, it did not work from the host - however in the container I was able to execute but got this

```
nonroot@bf32de477f19:/bing-rewards/BingRewards$ python BingRewards.py -nsb

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=True, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Wed, Oct 26 2022 03:21PM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "/bing-rewards/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/bing-rewards/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/bing-rewards/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/bing-rewards/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/bing-rewards/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/bing-rewards/BingRewards/src/rewards.py", line 242, in get_dashboard_data
    self.driver.find_element(By.XPATH, '/html/body').get_attribute('innerHTML'),
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 106, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 118, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/nonroot/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body"}
  (Session info: headless chrome=106.0.5249.119)
Stacktrace:
#0 0x561a1d71d2c3 <unknown>
#1 0x561a1d52683a <unknown>
#2 0x561a1d55f985 <unknown>
#3 0x561a1d55fb61 <unknown>
#4 0x561a1d597d14 <unknown>
#5 0x561a1d57df6d <unknown>
#6 0x561a1d595a50 <unknown>
#7 0x561a1d57dd63 <unknown>
#8 0x561a1d5527e3 <unknown>
#9 0x561a1d553a21 <unknown>
#10 0x561a1d76b18e <unknown>
#11 0x561a1d76e622 <unknown>
#12 0x561a1d751aae <unknown>
#13 0x561a1d76f2a3 <unknown>
#14 0x561a1d745ecf <unknown>
#15 0x561a1d78f588 <unknown>
#16 0x561a1d78f706 <unknown>
#17 0x561a1d7a98b2 <unknown>
#18 0x7f53ca83eea7 <unknown>
```

**Comment by JourneyOver** [comment] 2022-10-26 20:00
> > @Lexxior that's because it hasn't even done it's first "actual" run, you have to wait the alloted time in your cron before it does it's run and starts to fill out the logs.
> 
> I waited more than 2 hours, yet nothing changed


Did you change the cronjob to be of 2 hours or less? As the Default cronjob is every 8 hours, so unless you waited for the 8 hours you won't see anything unless you manually go in and run the stuff yourself.

**Comment by Lexxior** [comment] 2022-10-27 08:40
> > > @Lexxior that's because it hasn't even done it's first "actual" run, you have to wait the alloted time in your cron before it does it's run and starts to fill out the logs.
> > 
> > 
> > I waited more than 2 hours, yet nothing changed
> 
> Did you change the cronjob to be of 2 hours or less? As the Default cronjob is every 8 hours, so unless you waited for the 8 hours you won't see anything unless you manually go in and run the stuff yourself.

Thanks, I didn't realise this was what you meant in your last comment
I left it running overnight and it looks like it did something, as I had a few more points in the morning - but it seemed there were some errors
I just ran `BingRewards.py -nsb` after logging in the container and look - it worked, I got all points!
I will setup a crontab job that just runs that command every couple of hours until everything is merged

Thanks both of you!

**Comment by Killerherts** [comment] 2022-10-27 12:26
> > > > @Lexxior that's because it hasn't even done it's first "actual" run, you have to wait the alloted time in your cron before it does it's run and starts to fill out the logs.
> > > 
> > > 
> > > I waited more than 2 hours, yet nothing changed
> > 
> > Did you change the cronjob to be of 2 hours or less? As the Default cronjob is every 8 hours, so unless you waited for the 8 hours you won't see anything unless you manually go in and run the stuff yourself.
> 
> Thanks, I didn't realise this was what you meant in your last comment
> I left it running overnight and it looks like it did something, as I had a few more points in the morning - but it seemed there were some errors
> I just ran `BingRewards.py -nsb` after logging in the container and look - it worked, I got all points!
> I will setup a crontab job that just runs that command every couple of hours until everything is merged
> 
> Thanks both of you!

I'll double check my logs but I think the script is working as intended you just need to change the SCH environment var to `0 */2 * * *`

**Comment by jjjchens235** [comment] 2022-11-15 00:57
Killerhert's [PR](https://github.com/jjjchens235/bing-rewards/pull/294)- which fixes these issues- was merged to dev and will be merged to master soon.

**Closed by jjjchens235** 2022-11-15 00:57 UTC
