### ISSUE TITLE
All searches failing

### ISSUE THREAD

**Issue by raphalation** [jjjchens235/bing-rewards#49] opened 2020-10-08 21:09 UTC
Hi,

Just yesterday all my searches have been failing using the bing rewards program. I can still complete them manually. This is what my logs look like while it is running 

Enter   w for web,
        m for mobile,
        b for both,
        o for offers,
        a for all,
        r for remaining (default)
Input:
['Thu, Oct 08 2020 09:47AM', 'Failed Edge Search, Web Search, Mobile Search, Offers']

        You selected remaining

> Starting Edge search

DevTools listening on ws://127.0.0.1:55447/devtools/browser/b7993d06-7546-4df8-89e3-ab4ef7022b0b
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [                              ] 0/12 (0%)
           << Failed to complete search
    < Failed to complete edge search

> Starting web search
       >> Starting search
              >>> Progress: [                              ] 0/90 (0%)
           << Failed to complete search
    < Failed to complete web search

> Starting offers
       >> Trying Happy birthday!
           << Already checked
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Space week
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                     >>>> Progress: [                              ] 0/10 (0%)
                  <<< Failed to complete quiz2
           << Failed to complete Space week
       >> Trying Halloween fan?
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Halloween fan?
       >> Trying No more plastic
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete No more plastic
       >> Trying Daily Solitaire

Any ideas what the problem could be? I've tried redownloading the program from scratch and entering my details but no luck.

**Comment by jjjchens235** [comment] 2020-10-09 15:45
Closing as this is a duplicate of an unresolved issue: https://github.com/jjjchens235/bing-rewards/issues/37#issuecomment-690612357

**Closed by jjjchens235** 2020-10-09 15:45 UTC
