### ISSUE TITLE
Error checking rewards status, with empty message

### ISSUE THREAD

**Issue by icanotc** [jjjchens235/bing-rewards#91] opened 2021-09-06 03:51 UTC
it seems like Microsoft changed their rewards page, now this program cant do the offers anymore

![image](https://user-images.githubusercontent.com/44480394/132158091-58babbae-5652-4a34-a90a-6643813794d0.png)

very strange, going to try fixing this myself when I got time. 
haven't done python in a while, open to ideas on how to fix this. 

does anyone know where I can set headless mode to false?

**Comment by jjjchens235** [comment] 2021-09-06 11:17
This is a duplicate of [issue 88](https://github.com/jjjchens235/bing-rewards/issues/88)

Please use the most recently updated code, if that doesn't work please re-open 88.

**Closed by jjjchens235** 2021-09-06 11:17 UTC
