### ISSUE TITLE
Offers not working. They apparently fail immediately. 

### ISSUE THREAD

**Issue by daedalus311** [jjjchens235/bing-rewards#90] opened 2021-09-04 01:18 UTC
I start the BingRewards.py script with "--offers"  Output:

['Fri, Sep 03 2021 11:26AM', 'Failed Offers']

        You selected remaining

> Starting offers

This happens on 3 of my machines. I put the geckodriver inside the python home folder. I have the requirements.txt files installed.

Here is my run.log:
Fri, Sep 03 2021 07:36AM: Failed Offers
Fri, Sep 03 2021 10:24AM: Failed Offers
Fri, Sep 03 2021 11:19AM: Failed Offers
Fri, Sep 03 2021 11:20AM: Failed Offers
Fri, Sep 03 2021 11:26AM: Failed Offers
Fri, Sep 03 2021 09:10PM: Failed Offers

The same thing happens whether I pick all, offers, or searches...in any combination.  I see in the log.py it might possibly be saying the offers aren't completed...but they are because I manually did them; 3 green checks across the dailies.

Any help would be appreciated!

**Comment by webdeck** [comment] 2021-09-04 05:05
Here is where it is failing for me on the offers:

It seems to be failing on this page after it signs in: https://rewards.microsoft.com/welcome?idru=%2F%3Fredref%3Damc

![131858097-393a1a5f-a363-4a69-8b5f-92f833fa8225](https://user-images.githubusercontent.com/5542961/132083186-e989dc37-60e8-4a0e-a9f2-62e3c98f00cc.png)

**Comment by jjjchens235** [comment] 2021-09-04 18:16
this is a duplicate of this [issue](https://github.com/jjjchens235/bing-rewards/issues/88), thanks for the link will look into it.

**Closed by jjjchens235** 2021-09-04 18:16 UTC
