### ISSUE TITLE
Selenium Expection

### ISSUE THREAD

**Issue by FeelsBadMan1** [jjjchens235/bing-rewards#86] opened 2021-08-13 09:07 UTC
Hello, i ran this tool and some things worked but now im facing this error traceback:
```
       >> Trying Quiz-Kaffeepause
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [####################          ] 2/3 (66%)
                  <<< Failed to complete quiz1 - tried every choice
           << Failed to complete Quiz-Kaffeepause
[0813/090200.002:ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -101
       >> Trying Bonus Quiz
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 136, in <module>
    __main(args[0], arg1)
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 82, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 950, in complete_all
    self.__complete_offers(driver)
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 867, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 778, in __offers
    c = self.__click_offer(driver, offer, './div[2]/h3', './mee-rewards-points/div/div/span[1]', './div[2]/p', './div[3]/a/span/ng-transclude')
  File "C:\Users\Administrator\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 681, in __click_offer
    offer.find_element_by_xpath(link_xpath).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 226, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <ng-transclude>...</ng-transclude> is not clickable at point (767, 70). Other element would receive the click: <a href="/services" role="menuitem" data-bi-id="sh-sharedshell-services" aria-label="..." class="ms-Link root-55">Services &amp; subscriptions</a>
  (Session info: headless chrome=92.0.4515.131)
  ```

**Comment by daedalus311** [comment] 2021-09-04 01:07
Same issue. Ever get this fixed?

**Comment by jjjchens235** [comment] 2021-09-05 10:42
I have not encountered this issue and am unsure how to replicate it.

Are these happening for daily sets?

**Comment by bwalsh1028** [comment] 2021-09-07 12:01
I've gotten this error and the following every day as of a little while ago.
```
> Starting offers
<class 'selenium.common.exceptions.NoSuchElementException'>
    < Failed to complete offers
```

**Comment by jjjchens235** [comment] 2021-09-07 13:03
> I've gotten this error and the following every day as of a little while ago.
> 
> ```
> > Starting offers
> <class 'selenium.common.exceptions.NoSuchElementException'>
>     < Failed to complete offers
> ```

Duplicate of this [issue](https://github.com/jjjchens235/bing-rewards/issues/88), please use the most updated code.

**Closed** 2021-11-07 12:51 UTC
