### ISSUE TITLE
Getting selenium exception when starting offers

### ISSUE THREAD

**Issue by iTaKK** [jjjchens235/bing-rewards#88] opened 2021-09-02 18:26 UTC
Getting this error when starting offers, seems to fail every time i restart the bot

> Starting web search
       >> Starting search
              >>> Progress: [##############################] 150/150 (100%)
           << Successfully completed search
    < Successfully completed web search

> Starting offers
<class 'selenium.common.exceptions.NoSuchElementException'>
    < Failed to complete offers

> Starting mobile search

**Comment by wastingoctober** [comment] 2021-09-03 14:41
I'm experiencing this issue as well. Running Chrome 93.0.4577.63 and chromedriver 93.0.4577.15.

**Comment by daedalus311** [comment] 2021-09-03 15:04
same as me.  I have everything installed properly and everything else works.  I put the geckodriver inside the PATH (Python folder). It's something with Selenium or that chrome driver but I have no idea what the problem is.

**Comment by daedalus311** [comment] 2021-09-03 15:27
Fri, Sep 03 2021 11:20AM
Traceback (most recent call last):
  File "C:\Users\daeda\Downloads\BingBot2\BingRewards\BingRewards.py", line 75, in __main
    rewards.complete_offers()
  File "C:\Users\daeda\Downloads\BingBot2\BingRewards\src\rewards.py", line 936, in complete_offers
    driver = self.__complete_offers()
  File "C:\Users\daeda\Downloads\BingBot2\BingRewards\src\rewards.py", line 865, in __complete_offers
    self.__login(driver)
  File "C:\Users\daeda\Downloads\BingBot2\BingRewards\src\rewards.py", line 83, in __login
    ActionChains(driver).send_keys(base64.b64decode(self.email).decode(), Keys.RETURN).perform()
  File "C:\Python\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\Python\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Python\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 192, in _wrap
    result = attrib(*args, **kwargs)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=92.0.4515.159)

**Comment by webdeck** [comment] 2021-09-04 05:06
It seems to be failing on this page for offers after logging in: https://rewards.microsoft.com/welcome?idru=%2F%3Fredref%3Damc

![131858097-393a1a5f-a363-4a69-8b5f-92f833fa8225](https://user-images.githubusercontent.com/5542961/132083203-ac7c60bc-75f1-41f5-9f52-580f9e8d210f.png)

**Comment by wastingoctober** [comment] 2021-09-04 15:34
That’s interesting because that page isn’t new. Also, it’s still able to do the searches regardless.

**Comment by jjjchens235** [comment] 2021-09-04 18:18
I'm looking into this now. It looks like once you click 'sign in' then you're redirected back to the dashboard (which is good). 

However, after including that in the Selenium flow, I'm running into a different error. Will look more closely at this, want to get this fixed asap.

**Comment by wastingoctober** [comment] 2021-09-04 18:23
> I'm looking into this now. It looks like once you click 'sign in' then you're redirected back to the dashboard (which is good).
> 
> However, after including that in the Selenium flow, I'm running into a different error. Will look more closely at this, want to get this fixed asap.

thanks so much!

**Comment by wenzdey** [comment] 2021-09-04 20:45
> 
> 
> I'm looking into this now. It looks like once you click 'sign in' then you're redirected back to the dashboard (which is good).
> 
> However, after including that in the Selenium flow, I'm running into a different error. Will look more closely at this, want to get this fixed asap.

I find if I go to these urls after login it eventually pass that page.

https://rewards.microsoft.com/Signin
https://account.microsoft.com/rewards

**Comment by jjjchens235** [comment] 2021-09-05 00:23
The different error that I was referring to turns out to be a change in all the xpaths. This is going to take me a little bit of time to figure out all the new xpaths. Will keep working on it.

**Comment by jjjchens235** [comment] 2021-09-05 01:04
Ok I think I have the fix. If everything runs ok tmrw I'll upload.

**Comment by daedalus311** [comment] 2021-09-05 01:22
Thanks, mate. You're the best!

**Comment by iTaKK** [comment] 2021-09-05 02:59
Thanks, looking forward to the fix!

**Comment by thanatos216** [comment] 2021-09-05 04:23
Awesome.. can't wait.

**Comment by jjjchens235** [comment] 2021-09-05 10:31
This should be fixed! Please let me know if you run into issues still.

**Closed by jjjchens235** 2021-09-05 10:31 UTC

**Comment by wastingoctober** [comment] 2021-09-05 12:26
it’s still generating an error on my account. I made sure that I’ve pulled the latest code. we don’t need to go back through setup or anything, right? everything is working except the tasks.

**Comment by jjjchens235** [comment] 2021-09-05 17:16
Shit you scared me lol! Good news!

**Comment by gardncol** [comment] 2021-09-13 23:56
I am having this issue as well, offers have failed since Aug 30.

**Comment by daedalus311** [comment] 2021-09-14 00:20
https://github.com/h4x0rm1k3/ABS

This github has been updated and works.  We figured out theres a line of
code that needs changed every 28 days.  He updates it monthly.  I don't
want to drive people away from here but I also want everyone to reap the
benefits :)

**Comment by gardncol** [comment] 2021-09-14 02:36
Yep, I realized it was an issue with my pull script, which is why I deleted my comment. Once I updated it worked well. Thank you!
