### ISSUE TITLE
Any way to fix the error "find_element_by_* commands are deprecated. Please use find_element() instead"?

### ISSUE THREAD

**Issue by Gigafrost** [jjjchens235/bing-rewards#106] opened 2021-11-05 13:19 UTC
While running the scrtipt I noticed that it keeps throwing this error:
"find_element_by_* commands are deprecated. Please use find_element() instead"

I don't think it hinders the script for the most part, but I do notice that it seems to miss a lot of the quizzes sometimes, causing me to re-run the script. I'm kind of nervous that the bot's behaviour would be detected with multiple runs and was wondering if an update to the script to instead use the find_element() tag instead is underway?

ALSO off topic but is there any way to get Mobile search offers working? It says "Failed Mobile Search" each time.

Thanks and great job on this script!

**Comment by jjjchens235** [comment] 2021-11-05 23:21
Hey great point, I haven't upgraded to Selenium 4.0 so I haven't gotten this error message yet- appreciate the callout.
I'll definitely get a fix for this soon.

I haven't seen any major issues with the quizzes but if there's a particular quiz or type of quiz that you notice has an error, please call it out and I'll take a look.

Lastly, regarding mobile, I have seen this issue too. This issue has only cropped up recently where after ~9 successful searches, it tries to input a valid search string. 
For some reason, the browser/website does not take the input and the search field remains blank. Frankly, I have no idea what the issue is- not sure if it's on Bing's side or the driver's.

**Comment by Gigafrost** [comment] 2021-11-06 15:14
Sounds good. Thank you for the quick response as well! Other than the aforementioned bug your work is truly stellar!

I don't remember, but I believe it was the lightspeed one. It was the quiz that the script would say was ignored because it has an "overlay".

**Comment by jjjchens235** [comment] 2021-11-07 13:05
Thanks for the compliment!

Ok thanks for the call-out on the lightspeed.

I just updated the code and it should resolve this issue.

**Closed by jjjchens235** 2021-11-07 13:05 UTC
